version: '3'

services:
  keycloak:
    image: jboss/keycloak:12.0.4
    container_name: keycloak
    ports:
      - 8081:8080
    restart: always
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    volumes:
      - ../theme:/opt/jboss/keycloak/themes/cloakmail
      - ./disable-theme-cache.cli:/opt/jboss/startup-scripts/disable-theme-cache.cli